# .github/workflows/deploy-azure.yml
# Workflow to build the Docker image, push to GHCR, and deploy to Azure Web App

name: Build and Deploy to Azure Web App

env:
  # Set your Azure Web App name here
  AZURE_WEBAPP_NAME: 'solotype'
  # Set Node.js and pnpm versions used in Dockerfile and setup
  NODE_VERSION: '20'
  PNPM_VERSION: '8'
  # IMAGE_NAME is set dynamically in jobs

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permissions needed for the workflow
permissions:
  contents: read     # To checkout code
  packages: write    # To push container images to GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false # We'll install dependencies in Docker

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Define lowercase image name
        run: |
          REPO_OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
          REPO_NAME_LC=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/${REPO_OWNER_LC}/${REPO_NAME_LC}/solotype-frontend" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry using the GITHUB_TOKEN
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to GHCR
      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          file: ./Dockerfile
          build-args: |
            NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
            NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
            NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
            NODE_VERSION=${{ env.NODE_VERSION }}
            PNPM_VERSION=${{ env.PNPM_VERSION }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}

  deploy:
    # Deploy job runs only after the build job succeeds
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production' # Optional: Define a GitHub environment for protection rules
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} # Output the deployed URL

    steps:
      # Redefine the lowercase image name for this job
      - name: Define lowercase image name
        run: |
          REPO_OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
          REPO_NAME_LC=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/${REPO_OWNER_LC}/${REPO_NAME_LC}/solotype-frontend" >> $GITHUB_ENV

      # Login to Azure using the Service Principal credentials stored in secrets
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App using the container image from GHCR
      - name: Deploy to Azure Web App
        id: deploy-to-webapp # Give the step an ID to reference its outputs
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: '${{ env.IMAGE_NAME }}:${{ github.sha }}'

      # Optional: Logout from Azure
      - name: Logout from Azure
        run: az logout
        if: always() # Run this even if previous steps fail
